-- employee
 create table public.employee(
     id int GENERATED BY DEFAULT AS IDENTITY,
     staff_id int not null,
     staff_name text NOT NULL,
     email text NOT NULL,
     password text NOT NULL,
     supervisor_id text NOT NULL,
     sex text NOT NULL,
     division_id text NOT NULL,    
     location_user text NOT NULL,
     staff_level text NOT NULL,
     joined_date text NOT NULL,
     created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
     updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
     deleted_at timestamp with time zone,
	token text
 );

 ALTER TABLE ONLY public.employee ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


CREATE TABLE leave_detail(
    id int GENERATED BY DEFAULT AS IDENTITY,
    start_date text,
    end_date text,
    leave_id int,
    remarks text,
    submission_date text,
	status text,
	read_staff text,
    read_supervisor text,
    record_id text,
    process_id text,
    staff_id int
);

ALTER TABLE ONLY public.leave_detail ADD CONSTRAINT leave_detail_pkey PRIMARY KEY (id);


--- Division
---  Division objek division
CREATE TABLE public.division (
    id int GENERATED BY DEFAULT AS IDENTITY,
    division_name text NOT NULL
);
ALTER TABLE ONLY public.division ADD CONSTRAINT division_pkey PRIMARY KEY(id);


--- UNIT 
--- UNIT objek UNIT
CREATE TABLE public.unit (
    id int GENERATED BY DEFAULT AS IDENTITY,
    unit_name text NOT NULL,
    division_name text NOT NULL
);

ALTER TABLE ONLY public.unit ADD CONSTRAINT unit_pkey PRIMARY KEY (id);

--- Leave
--- Leave objek Leave 
CREATE TABLE public.leave (
    id int GENERATED BY DEFAULT AS IDENTITY,
    leave_name text NOT NULL,
    type text NOT NULL,
    entitlement int not null 
);

ALTER TABLE ONLY public.leave ADD CONSTRAINT leave_pkey PRIMARY KEY (id);


--- Holiday
--- Holiday objek Holiday
CREATE TABLE public.holiday(
    id_holiday int GENERATED BY DEFAULT AS IDENTITY,
    holiday_name text NOT NULL,
    holiday_date text NOT NULL
);
ALTER TABLE ONLY public.holiday ADD CONSTRAINT holiday_pkey PRIMARY KEY (id_holiday);

insert into employee (staff_id, staff_name, email, password, supervisor_id, sex, division_id, location_user, staff_level, joined_date, token) values 
	(2018112001, 'Fahmi Prasetio', 'fahmiprasetiiio@gmail.com', '123123', '2', 'L','none', 'Bandung', 'Staff', '22-11-2017', 'iYwlxotIP5MQP-U31UJB6Lbv3uzo4gnRq4i1PKkMeTo.n-818ucaKcayquy2ltXXAOnAoyU9mAdVYMHedaiFL3k'),
	(2018112002, 'Samsam Muhammad Nursamsi', 'samsam.nursamsi02@gmail.com', '123123', '3', 'L','none', 'Tasikmalaya', 'Supervisor', '22-11-2015', 'gUrYSFPPM7bPAWcagU-NL9xfVgyJghDTZP3gyy0GthM.IhPwLzimPNIY1FkKju2PsVtu_jpZcSIFDoYLSSWV1SI'),
	(2018112003, 'Cecep Ahmad Fauzi', 'samsam.nursamsi02@gmail.com', '123123', '0', 'L','none', 'Bandung', 'Manager', '22-11-2012',''),
	(2018112004, 'Yamato Kazuka', 'fahmiprasetiiio@gmail.com', '123123', '2', 'L','none', 'Jakarta', 'Staff', '22-08-2016',''),
	(2018112005, 'Tensi Agusa', 'fahmiprasetiiio@gmail.com', '123123', '2', 'L','none', 'Semarang', 'Staff', '22-10-2016',''),
	(2018112006, 'Arima Kishou', 'fahmiprasetiiio@gmail.com', '123123', '2', 'L','none', 'Majalaya', 'Staff', '22-08-2016',''),
	(2018112007, 'Tenma Kajuyo', 'fahmiprasetiiio@gmail.com', '123123', '2', 'L','none', 'Jakarta', 'Supervisor', '22-08-2012','');


insert into leave (leave_name, type, entitlement) VALUES
('Maternity Leave', 'Important',90),
('Miscarriage Leave', 'Important',45),
('Menstruation Leave', 'Important',2),
('Employees marriage Leave', 'Important',3),
('Marriage of Employees children', 'Important',2),
('Demise of wife / husband / child / parents / parents in-law', 'Important',2),
('Circumcision/Baptism of the Employees children', 'Important',2),
('Maternity of Employees wife', 'Important',2),
('Demise of Employees grandfather / grandmother', 'Important',1),
('Demise of sibling and / or family member registered in the Family Card', 'Important',1),
('Hajj (First time)', 'Free', 0),
('Request from Government / Court / Police', 'Free', 0),
('Medical Leave', 'Free', 0);